# Generated by Django 5.1.4 on 2024-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
