# Generated by Django 5.1.4 on 2024-12-11 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_studentdetails_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='mobile',
        ),
    ]
